# Generated by Django 2.1.7 on 2019-03-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_archived',
            field=models.BooleanField(default=False),
        ),
    ]
