# Generated by Django 2.1.7 on 2019-03-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.CharField(error_messages={'required': 'Please, enter task text'}, max_length=255),
        ),
    ]
