# Generated by Django 2.1.7 on 2019-03-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20190309_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysession',
            name='user_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
